gross_not_negative:
  applies_to:
  - total_gross_profit
  - frontend_gross
  - backend_gross
  column: total_gross_profit
  message: Gross profit should not be negative
  operator: '>='
  severity: high
  threshold: 0
  type: comparison
max_days_in_inventory:
  column: days_in_inventory
  message: Days in inventory should not exceed 90 days
  operator: <=
  severity: medium
  threshold: 90
  type: comparison
min_be_penetration:
  column: be_penetration
  message: Back end penetration should be at least 70%
  operator: '>='
  severity: low
  threshold: 70
  type: comparison
min_close_rate:
  column: close_rate
  message: Close rate should be at least 8%
  operator: '>='
  severity: medium
  threshold: 8
  type: comparison
min_gross_per_unit:
  column: gross_profit_per_unit
  message: Gross profit per unit should be at least $500
  operator: '>='
  severity: medium
  threshold: 500
  type: comparison
price_below_cost:
  column: price
  message: Selling price should be higher than cost
  operator: '>'
  severity: high
  threshold:
    column: cost
  type: comparison
revenue_matching:
  condition: revenue >= (units_sold * avg_selling_price)
  message: Revenue should match or exceed calculated value from units sold
  severity: high
  type: custom
sale_date_range:
  column: sale_date
  max_value: TODAY
  message: Sale date must be between 2020 and today
  min_value: '2020-01-01'
  severity: high
  type: range
valid_vin:
  column: vin
  message: VIN must be 17 characters and contain only valid characters
  pattern: ^[A-HJ-NPR-Z0-9]{17}$
  severity: medium
  type: regexp
