version: '3.8'

services:
  web:
    build: .
    ports:
      - "8501:8501"
    volumes:
      # Mount these directories for development to allow live code changes
      - ./src:/app/src
      - ./assets:/app/assets
      - ./profiles:/app/profiles
      - ./prompt_templates:/app/prompt_templates
    environment:
      - DEBUG=true
    restart: unless-stopped
    depends_on:
      - redis
  
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: