name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run unit tests
      run: |
        pytest --maxfail=1 --disable-warnings -q
        
    - name: Start Streamlit server
      run: |
        nohup streamlit run src/ui/streamlit_app.py &
        # Wait for server to be ready
        timeout 30 bash -c 'until curl --output /dev/null --silent --head --fail http://localhost:8501; do sleep 1; done'
        
    - name: Run E2E tests
      run: |
        pytest tests/e2e/ --capture=no
        
    - name: Run smoke tests
      run: |
        python scripts/smoke_insights.py
        
    - name: Build Docker image
      run: |
        docker build . -t watchdog:ci
      if: success()
      
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install linting dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 src/ --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics